version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: 34.11.220.37
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Algoma@2024
      DB_NAME: postgres
      JWT_SECRET: 12DH9111hbhos5AW
      GEMINI_KEY: AIzaSyBHsvcGZKwjuW0ohOjiBW7kBws8say3no0
    depends_on:
      postgres:
        condition: service_healthy
    # Use Google DNS to fix NXDOMAIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Optional: increase network timeout and make container more resilient
    restart: unless-stopped
    networks:
      - nordik-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 876h#GFGFGFHHJHJ
      POSTGRES_DB: nordik_drive
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - nordik-network

volumes:
  pgdata:

networks:
  nordik-network:
    driver: bridge
